bundler_args: "--without development"
before_script:
    - "cp config/database.ci.yml config/database.yml"
    - "cp config/app_config.sample.yml config/app_config.yml"
    - "mysql -e 'create database rnews_test;' > /dev/null"
    - "bundle exec rake db:migrate"
    - "echo \"Rnews::Application.config.secret_token = '$(bundle exec rake secret)'\" > config/initializers/secret_token.rb"
script: "bundle exec rake test"
notifications:
    email: false

rvm:
    - 1.9.2
    - 1.9.3
